name: Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          choco install doxygen.install graphviz
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install doxygen graphviz
        fi

    - name: Generate Documentation
      run: doxygen Doxyfile
