name: Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Install Doxygen (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install doxygen.install graphviz

    - name: Install Doxygen (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install doxygen graphviz

    - name: Generate Documentation
      run: doxygen Doxyfile